- name: install docker
  import_tasks: docker-ins.yml

- name: install vpn
  import_tasks: softEther-vpn.yml
#      - name: Install aptitude using apt
#        apt:
#          name: aptitude
#          state: latest
#          update_cache: yes
#          force_apt_get: yes          
#  
#      - name: Install required system packages
#        apt: name={{ item }} state=latest update_cache=yes
#        loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
#  
#      - name: Add Docker GPG apt Key
#        apt_key:
#          url: https://download.docker.com/linux/ubuntu/gpg
#          state: present
#  
#      - name: Add Docker Repository
#        apt_repository:
#          repo: deb https://download.docker.com/linux/ubuntu focal stable
#          state: present
#  
#      - name: Update apt and install docker-ce
#        apt:
#          update_cache: yes
#          name: docker-ce
#          state: latest
#  
#      - name: Install Docker Module for python
#        pip:
#          name: docker
#      
#      - name: Login to registry
#        docker_login:
#          registry_url: https://docker.io
#          username: "{{ dockerhub_username }}"
#          password: "{{ dockerhub_password }}"
#  
#      - name: pull SoftEther VPN docker image
#        docker_image:
#          name: "{{ default_container_image }}"
#          source: pull
#  
#      - name: Create SoftEther container
#        docker_container:
#          name : "{{ default_container_name }}"
#          image: "{{ default_container_image }}"
#          state: started
#          ports:
#           - "500:500/udp"
#           - "4500:4500/udp"
#           - "1701:1701/tcp"
#           - "1194:1194/udp"
#          capabilities:
#            - NET_ADMIN
#  


# tasks file for Docker
