---
     
      - name: pull SoftEther VPN docker image
        docker_image:
          name: "{{ default_container_image }}"
          source: pull

      - name: Create SoftEther container
        docker_container:
          name : "{{ default_container_name }}"
          image: "{{ default_container_image }}"
          state: started
          ports:
           - "500:500/udp"
           - "4500:4500/udp"
           - "1701:1701/tcp"
           - "1194:1194/udp"
          capabilities:
            - NET_ADMIN
